### ISSUE TITLE
wurlitzer works only in a debug mode.

### ISSUE THREAD

**Issue by lpravda** [minrk/wurlitzer#14]
Hi,

I've come across this library and I experience some really odd behaviour, which completely puzzles me. My machine setting is as follows:

MAC OS: 10.13.3
Conda:  4.5
Python 3.6.1
vscode: 1.22.1

I'm trying to catch C++ output from the package called RDkit (https://github.com/rdkit/rdkit) which exposes some of its functionality over python package with the same name. with the following code (prints are just for tracking of the progress):

```python
    with io.BytesIO() as stream:
            print('a')
            with pipes(stder=stream):
                print('b')
                while ((not success) and attempts >= 0):
                    print('c')
                    ....
```

When I try to run it in vscode debug mode everything works smoothly. **a, b** and **c** gets print out properly, stream variable is filled with the proper content and everything works smoothly. However, When I try to run the very same code from command line. Only **a** is printed like the rest of the function did not exist at all. The minimal example exhibiting this behaviour is this:

```python
from wurlitzer import pipes
import io
from rdkit import Chem

mol = Chem.MolFromSmiles('c1cccc1', sanitize=False)

with io.BytesIO() as stream:
    with pipes(stderr=stream):
        result = Chem.SanitizeMol(mol, catchErrors=True)
        status = stream.getvalue().decode('utf-8')
        print('Rdkit said {}'.format(status))
```

however it requires rdkit to be installed through conda channel:

conda create -c rdkit -n my-rdkit-env rdkit python=3.6.1

I also tried the same one with rh-7 and the terminal exhibits the same behaviour. Any thoughts?

**Comment by minrk** [comment]
I know it's been 3 years, but I am checking in on some repos now.

I believe the main issue is calling `.getvalue()` within the `pipes` context manager. Because pipe capture happens using threads, you are not guaranteed that the captured output has propagated until/unless you flush things. The simplest way to do that is by moving your `stream.getvalue()` *outside* the context manager:

```python
with pipes(stderr=stream):
    result = Chem.SanitizeMol(mol, catchErrors=True)
status = stream.getvalue()
```

Because wurlitzer tries pretty hard to flush pipes as it exits the context.

You *can* call flush inside, but there would still be threading issues.

Instead, I'd recommend using `with pipes()` for *each* call you want to capture and read.
