### ISSUE TITLE
sys.__stdout__ can be None

### ISSUE THREAD

**Issue by impact27** [minrk/wurlitzer#36]
See https://github.com/spyder-ide/spyder-kernels/issues/191

According to https://docs.python.org/3.8/library/sys.html#sys.__stderr__:

> Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw. 

This line:
https://github.com/minrk/wurlitzer/blob/b30ae5df29114b4824bf078391af5e2dba0344ee/wurlitzer.py#L107
Assumes they are not. Should there be an extra test? I am not sure how to handle this error.

**Comment by minrk** [comment]
Good question! Wurlitzer won't be able to capture output if this happens, I think, so it's a bit unclear if it should warn or raise, but it should probably be one or the other. My guess is, given the context, that Wurlitzer itself should raise (since it's failing to do what you are asking it to), but the *IPython extension* should demote that to a warning.
