### ISSUE TITLE
Wurlitzer does not release file descriptors

### ISSUE THREAD

**Issue by jamitr-jci** [minrk/wurlitzer#46]
### Bug description

When looping over a function and trying to capture C level errors I get growing number of file handlers. 
`ls /proc/<PID>/fd/ | wc -l` -> yields growing numbers over time.
My code is similar to:
```
from wurlitzer import pipes
while not stopped:
    with pipes() as (out, err):
        res = some_c_func()

    c_error = err.read()

    if len(c_error) > 0:
        logger.error(c_error )
```
#### Expected behaviour

I would expect it to close the handlers.
#### Actual behaviour

The fd are not closing, adding:
```
err.close()
out.close()
del err,out,c_error
```
at the end of each loop does not help.

### How to reproduce

Use a similar code as above.

### Your personal set up

 - OS:
Ubuntu 18.04.05LTS
 - Version:
Python 3.8, Wurlitzer 2.0.1

**Comment by minrk** [comment]
Thanks for the report! Should be fixed by #47.

There was an FD that was relying on garbage collection to close it, so calling `gc.collect()` explicitly ought to solve it.

I  ran this test on `python:3.8` docker image and after thousands of iterations, the fd count never exceeded 44, and always reset back to 8 after a few dozen iterations (whenever the garbage collector gets called):

```python
import ctypes
import gc
import os
import time
from itertools import count

from wurlitzer import pipes

printf = ctypes.CDLL(None).printf

pid = os.getpid()
fd_dir = f"/proc/{pid}/fd"


hwm = 0
for i in count():
    num_fds = len(os.listdir(fd_dir))
    hwm = max(num_fds, hwm)
    print(f"{i:4}: fds={num_fds:03}, max={hwm:03}")
    with pipes() as (out, err):
        printf(b"hmm\n")
    # gc.collect() # no growth
    time.sleep(0.05)
```

With #47, the FD count never exceeds 6.
